FROM openjdk:8
EXPOSE 7070
ADD ProjectManagement-0.0.1-SNAPSHOT.jar ProjectManagement-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "ProjectManagement-0.0.1-SNAPSHOT.jar"]
RUN sh -c 'touch /ProjectManagement-0.0.1-SNAPSHOT.jar'